# Generated by Django 4.1.2 on 2022-11-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"ordering": ["-updated"]},
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(max_length=65),
        ),
    ]
