# Generated by Django 4.1.2 on 2022-11-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_story_options_alter_story_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="Story",
            field=models.TextField(null=True),
        ),
    ]
